#!/bin/sh
#
# Download and install Composer with single command.


# Chech whether PHP is available on your system.
if ! command -v php -v 2>&1 >/dev/null;
then
    echo "No PHP on the system" >&2;
    exit 1;
fi

prefix=$1;

# Fallback to $HOME/bin
if [ -z "$prefix" ];
then
    prefix="${HOME}/bin";
fi

# Create a directory if it doesn't exist.
if ! [ -d "$prefix" ];
then
    mkdir -p "$prefix" || (
        echo "Fails to create the directory $prefix" >&2;
        exit 1;
    )
fi

# Download and install Composer.
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === '756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php --install-dir="$prefix" --filename=composer
php -r "unlink('composer-setup.php');"

echo "Add $prefix to PATH variable to use composer";
