#!/bin/sh

# Chech whether PHP is available on your system.
if ! command -v php --version 2>&1 >/dev/null;
then
    echo "No PHP on the system" >2;
    exit 1;
fi

# Create $HOME/bin.
if ! [ -d "$HOME/bin" ];
then
    mkdir -p "$HOME/bin" || (
        echo "Fails to create the directory $HOME/bin";
        exit 1;
    )
fi

# Download and install Composer.
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === '756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php --install-dir=$HOME/bin --filename=composer
php -r "unlink('composer-setup.php');"

echo "Add $HOME/bin to PATH variable to use composer";