#!/bin/sh
#
# Sync the local repo to a production environment.
#  Unrequired directories and files are skipped.


# Check whether `rsync(1)` is available.
if ! command -v rsync -h 2>&1 >/dev/null;
then
    echo "No rsync on the system" >&2;
    exit 1;
fi

# Get some destination.
dest=$1;
if [ -z "$dest" ];
then
    echo "No destination" >&2;
    exit 1;
fi

# Check whether the destination is valid.
if ! [ -d "$dest" ];
then
    echo "Invalid destination: $dest" >&2;
    exit 1;
fi

# Get the root path of the repo.
cwd="$(dirname $0)";
src="${cwd}/.."

# Copy static files.
cp -pr "$src/static/"* "$src/public" || (
    echo "Unable to copy static files to the public directory" >&2;
    exit 1;
)

# Sync between the source and the destination.
#  Files on the distination may be deleted.
#  Don't edit them.
rsync -rvh --delete \
    --exclude ".git*" \
    --exclude scripts \
    --exclude composer.json --exclude composer.lock \
    --exclude LICENSE --exclude README.md --exclude TODO.md \
    --exclude package.json --exclude package-lock.json --exclude node_modules \
    --exclude .browserlistrc --exclude .stylelintrc \
    --exclude .eslintrc --exclude .flowconfig \
    --exclude assets --exclude build --exclude static \
    "$src/" "$dest/";
