#!/bin/sh
# TODO: Test the script.

# Check whether `rsync(1)` is available.
if ! command -v rsync -h 2>&1 >/dev/null;
then
    echo "No rsync on the system" >&2;
    exit 1;
fi

# Get a destination.
dest=$1;
if [ -z "$dest" ];
then
    echo "No destination" >&2;
    exit 1;
fi

# Check whether the destination is valid.
if ! [ -d "$dest" ];
then
    echo "Invalid destination: $dest" >&2;
    exit 1;
fi

# Get the source.
cwd="$(dirname $0)";
src="${cwd}/.."

# Sync between the source and the destination.
# Files on the distination may be deleted. Don't edit them.
rsync -rvh --delete \
    --exclude ".git*" \
    --exclude scripts \
    --exclude "vendor*" \
    --exclude LICENSE \
    --exclude README.md \
    "$src" "$dest";
